---
author: Rodney J. Dyer
categories: ["R","RStudio","Dyerlab"]
date: 2017-01-08T06:12:59-05:00
description: "A brief synopsis of why all the change."
featured: ""
featuredalt: ""
featuredpath: ""
linktitle: ""
title: "New Server, New Site, First Post!"
---

This is the first post after moving the dyerlab web server off of WordPress and the *bio.vcu.edu domain.  I've made this move to simplify the information that I provide on the site, all integrated within a markdown/R context.  Yes, this blog and the entire website was written in [Rmarkdown](http://rmarkdown.rstudio.com/) using a blog-friendly packages called [blogdown](http://github.com/rstudio/blogdown) (thanks [yihui](https://github.com/yihui), you are a genius!) on a server instance of [RStudio](http://rstudio.com) hosted on an ubuntu virtual server owned by [Amazon Web Services](https://lightsail.aws.amazon.com)!  

One of the drawbacks of moving from a more closed system to an open one is that things may not translate as well.  I've tried to preserve the posts from the previous site here but translation from WordPress XML $\to$ Jeckyll $\to$ markdown may have tarnished their luster a bit.  I can honestly say that I'm not going to go back through posts of years past and reconfigure them so they work better. Sorry, just not going to happen.  

Given that drawback, I think the benefits of a consolidated web presence outweigh the problems.  Here are two of the main reasons I made this move.  

1. Posting of R-related content is easier if I do not have to cut-and-paste content, code, and images into a separate interface.  Having posts such as this one be a real Rmarkdown document simplify my life.  As a result, you get more access to R materials.  
2. I have posted the texts that I've written for classes I teach using R on this page (hidden behind the cleaverly worded menu item called 'Texts').  They will be here and available in perpituity.


In recognition of the hard work many groups have contributed for this mashup to actually function, I'll start by retelling a statistics joke in the following pie chart below. 


```{r pie, fig.cap='A fancy pie chart.', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Sky', 'Sunny side of pyramid', 'Shady side of pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

